// Detection rules. Each category has a weight (how much it raises risk) and
// a list of regexes. Everything runs locally in the browser.
// The slur list is intentionally explicit: you can't flag what you can't match.

const RISK_CATEGORIES = [
  {
    id: "slurs",
    label: "Slurs",
    weight: 10,
    hint: "Racial, homophobic, transphobic or ableist slurs. The #1 thing that gets people cancelled.",
    patterns: [
      /\bn[i1!|]gg(?:a|ah|as|az|er|ers|uh|uhs)\b/gi,
      /\bfag(?:s|got|gots|gy)?\b/gi,
      /\bretard(?:s|ed)?\b/gi,
      /\btard\b/gi,
      /\btrann(?:y|ies)\b/gi,
      /\bshemale\b/gi,
      /\bdykes?\b/gi,
      /\bspics?\b/gi,
      /\bchinks?\b/gi,
      /\bkikes?\b/gi,
      /\bwetbacks?\b/gi,
      /\bbeaners?\b/gi,
      /\bgooks?\b/gi,
      /\b(?:towel|rag)heads?\b/gi,
      /\bcoons?\b/gi,
      /\bjungle bunn(?:y|ies)\b/gi,
    ],
  },
  {
    id: "hate",
    label: "Stereotypes & bigotry",
    weight: 6,
    hint: "Generalizations about whole groups of people.",
    patterns: [
      /\ball (?:women|men|girls|guys|blacks|whites|mexicans|muslims|jews|gays|immigrants|asians|indians|christians|liberals|conservatives|trans people) (?:are|r)\b/gi,
      /\bgo back to (?:your|ur|their) (?:own )?country\b/gi,
      /\billegals\b/gi,
      /\bfemales (?:are|r|be)\b/gi,
      /\bwomen (?:belong|should stay) in the kitchen\b/gi,
      /\bmake me a sandwich\b/gi,
      /\bthat'?s so gay\b/gi,
      /\bno homo\b/gi,
      /\bwomen can'?t (?:drive|lead)\b/gi,
    ],
  },
  {
    id: "violence",
    label: "Violence & threats",
    weight: 7,
    hint: "Anything that reads like a threat, even as a joke.",
    patterns: [
      /\b(?:kill|shoot|stab|murder|strangle|choke)(?:ing)? (?:you|u|him|her|them|everyone|my (?:boss|teacher|ex))\b/gi,
      /\bi(?:'ll| will| would| wanna| want to| am gonna|'m gonna) (?:kill|shoot|stab|murder|punch|beat up|fight)\b/gi,
      /\bbomb (?:the|this|that)\b/gi,
      /\bshoot up\b/gi,
      /\bhope (?:you|u|he|she|they) die\b/gi,
    ],
  },
  {
    id: "harassment",
    label: "Insults & harassment",
    weight: 5,
    hint: "Attacking a person, especially when you @mention them.",
    patterns: [
      /\bkys\b/gi,
      /\bkill (?:yo)?urself\b/gi,
      /\bgo die\b/gi,
      /\b(?:you'?re|youre|ur|you are) (?:so |such an? |a |an )?(?:stupid|dumb|ugly|fat|worthless|pathetic|trash|garbage|loser|idiot|moron|clown|joke|waste)\b/gi,
      /\bnobody (?:likes|cares about) (?:you|u)\b/gi,
      /\bshut (?:the f\w* )?up\b/gi,
      /\b(?:idiot|moron|imbecile|dumbass|loser)s?\b/gi,
      /\bugly ass\b/gi,
    ],
  },
  {
    id: "sexual",
    label: "Sexual content",
    weight: 3,
    hint: "Fine for some audiences, awkward for employers and schools.",
    patterns: [
      /\bnudes?\b/gi,
      /\bhorny\b/gi,
      /\bporn\w*\b/gi,
      /\bthots?\b/gi,
      /\bhoes?\b/gi,
      /\bsluts?\b/gi,
      /\bwhores?\b/gi,
      /\bonlyfans\b/gi,
      /\b(?:had|having|want) sex\b/gi,
      /\bwould smash\b/gi,
    ],
  },
  {
    id: "body",
    label: "Body shaming",
    weight: 4,
    hint: "Comments about weight, looks or disability.",
    patterns: [
      /\bfat(?:ass|ty|ties|so)?\b/gi,
      /\bugly\b/gi,
      /\bmidgets?\b/gi,
      /\banorexic\b/gi,
      /\bneeds? to lose weight\b/gi,
    ],
  },
  {
    id: "drugs",
    label: "Drugs & partying",
    weight: 2,
    hint: "Recruiters and background checks notice these.",
    patterns: [
      /\bweed\b/gi,
      /\bblunts?\b/gi,
      /\bhigh af\b/gi,
      /\bstoned\b/gi,
      /\bcocaine\b/gi,
      /\bmolly\b/gi,
      /\bshrooms\b/gi,
      /\bxanax\b/gi,
      /\bpercs?\b/gi,
      /\b(?:sipping )?lean\b(?= |$)/gi,
      /\b(?:so |hella |super )?(?:drunk|wasted|hungover|faded|crossfaded)\b/gi,
      /\b420\b/g,
    ],
  },
  {
    id: "profanity",
    label: "Profanity",
    weight: 1,
    hint: "Low risk on its own, but adds up.",
    patterns: [
      /\bf+u+c+k+\w*\b/gi,
      /\bsh[i1]t\w*\b/gi,
      /\bbitch\w*\b/gi,
      /\bcunts?\b/gi,
      /\bdicks?\b/gi,
      /\bpuss(?:y|ies)\b/gi,
      /\bass(?:hole|holes|hat)?\b/gi,
      /\bbastards?\b/gi,
      /\b(?:wtf|stfu|gtfo|mf|mfs)\b/gi,
    ],
  },
  {
    id: "work",
    label: "Work & school",
    weight: 2,
    hint: "Trash-talking a job, boss, school or admitting to cheating.",
    patterns: [
      /\bmy (?:boss|manager|coworkers?|co-workers?|teacher|professor)\b/gi,
      /\bhate my (?:job|boss|work|school)\b/gi,
      /\bcall(?:ed|ing)? in sick\b/gi,
      /\bskip(?:ped|ping)? (?:class|work|school)\b/gi,
      /\bcheat(?:ed|ing)? on (?:the|my|a) (?:test|exam|quiz|final)\b/gi,
      /\bgot fired\b/gi,
    ],
  },
  // ----- Hot topics: not wrong to post, but hot takes here are what usually resurfaces. -----
  {
    id: "us_politics", group: "topics", label: "US politics", weight: 1,
    hint: "Politicians, parties and election takes.",
    patterns: [
      /(?:trump|biden|kamala|harris|obama|maga|vance|newsom|desantis|aoc|pelosi|fauci)/gi,
      /(?:democrats?|dems|republicans?|gop|libtards?|liberals?|conservatives?|leftists?|right ?wing(?:ers)?|commies?|fascists?)/gi,
      /(?:stolen|rigged) election|election (?:was )?(?:stolen|rigged)/gi,
      /(?:antifa|proud boys|defund the police|acab|jan(?:uary)? 6)/gi,
    ],
  },
  {
    id: "israel_palestine", group: "topics", label: "Israel / Palestine", weight: 2,
    hint: "One of the most scrutinized topics by employers and schools right now.",
    patterns: [
      /(?:israel(?:i|is)?|palestin(?:e|ian|ians)|gaza|west bank|zionis\w*|anti-?zionis\w*|hamas|idf|netanyahu|hezbollah|intifada)/gi,
      /from the river to the sea/gi,
      /free palestine/gi,
      /(?:oct(?:ober)? 7(?:th)?)/gi,
      /(?:genocide|apartheid|ceasefire)/gi,
    ],
  },
  {
    id: "abortion", group: "topics", label: "Abortion", weight: 1,
    hint: "Abortion and reproductive rights.",
    patterns: [/(?:abortions?|pro-?life|pro-?choice|roe v\.? wade|planned parenthood)/gi],
  },
  {
    id: "guns", group: "topics", label: "Guns", weight: 1,
    hint: "Gun control and gun rights.",
    patterns: [/(?:gun control|gun rights|2a|second amendment|nra|ar-?15s?|assault weapons?)/gi],
  },
  {
    id: "immigration", group: "topics", label: "Immigration", weight: 1,
    hint: "Border, deportation and immigration takes.",
    patterns: [/(?:immigra\w+|illegal aliens?|deport\w*|border wall|ice raids?|migrants?|asylum seekers?)/gi],
  },
  {
    id: "race", group: "topics", label: "Race", weight: 1,
    hint: "Race and racial-justice debates.",
    patterns: [/(?:blm|black lives matter|all lives matter|white privilege|critical race theory|crt|reparations|affirmative action|dei)/gi],
  },
  {
    id: "gender", group: "topics", label: "Gender & LGBTQ", weight: 1,
    hint: "Gender, trans and LGBTQ debates.",
    patterns: [/(?:trans(?:gender)?|pronouns|lgbtq?\w*|gay marriage|drag queens?|pride month|woke|feminis(?:m|ts?))/gi],
  },
  {
    id: "religion", group: "topics", label: "Religion", weight: 1,
    hint: "Takes on religions or religious groups.",
    patterns: [/(?:muslims?|islam\w*|christians?|christianity|jews?|jewish|atheis\w+|bible|quran|koran)/gi],
  },
  {
    id: "covid", group: "topics", label: "COVID & vaccines", weight: 1,
    hint: "Vaccine, mask and lockdown takes.",
    patterns: [/(?:vax|vaxx\w*|vaccines?|anti-?vax\w*|plandemic|covid hoax|mask mandates?|lockdowns?)/gi],
  },
];

// Personal info you may have leaked about yourself.
const PII_CATEGORIES = [
  { id: "phone", label: "Phone number", patterns: [/(?:\+?1[\s.-]?)?\(?\b\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}\b/g] },
  { id: "email", label: "Email address", patterns: [/\b[\w.+-]+@[\w-]+\.[\w.]{2,}\b/g] },
  { id: "ssn", label: "SSN-like number", patterns: [/\b\d{3}-\d{2}-\d{4}\b/g] },
  {
    id: "address",
    label: "Street address",
    patterns: [
      /\b\d{1,5} (?:[A-Z][a-z]+ ){1,3}(?:St|Street|Ave|Avenue|Rd|Road|Blvd|Boulevard|Dr|Drive|Ln|Lane|Ct|Court|Way|Pkwy|Parkway|Pl|Place|Cir|Circle)\b\.?/g,
      /\bmy (?:address|apartment|apt|house) (?:is|at)\b/gi,
    ],
  },
  {
    id: "location",
    label: "Where you live",
    patterns: [/\bi (?:live|stay) (?:in|on|at|near|by)\b[^.!?\n]{0,30}/gi, /\b(?:just )?moved to\b[^.!?\n]{0,30}/gi, /\bmy (?:neighborhood|hometown|street)\b/gi],
  },
  {
    id: "birthday",
    label: "Birthday & age",
    patterns: [/\bmy (?:birthday|bday|b-day)\b/gi, /\bturn(?:ed|ing)? \d{2}\b/gi, /\bi(?:'m| am) \d{2} (?:years old|yrs old|today)\b/gi, /\bborn (?:on|in) \w+/gi],
  },
  {
    id: "workplace",
    label: "Workplace",
    patterns: [/\bi work (?:at|for)\b[^.!?\n]{0,30}/gi, /\b(?:started|starting) (?:working )?at\b[^.!?\n]{0,30}/gi, /\bmy (?:job|shift) at\b[^.!?\n]{0,30}/gi],
  },
  {
    id: "school",
    label: "School",
    patterns: [/\bclass of 20\d\d\b/gi, /\b(?:freshman|sophomore|junior|senior) (?:at|in)\b[^.!?\n]{0,30}/gi, /\bi go to\b[^.!?\n]{0,25}(?:high|school|university|college|uni)\b/gi],
  },
  {
    id: "family",
    label: "Family details",
    patterns: [/\bmy (?:mom|dad|mother|father|son|daughter|kids?|wife|husband|sister|brother)(?:'s)? (?:name is|birthday|school)\b/gi],
  },
  { id: "payments", label: "Payment handles", patterns: [/\b(?:venmo|cash ?app|paypal\.me|zelle)\b[^.!?\n]{0,25}/gi] },
];
